title: Ivana Rebić # your name (or website title) here
# logo: "/images/logo.png?raw=true" # your photo (or logo) here/ umjesto logo.png ise ime foldera gdje se nalazi pa onda jepg ako je takva slika
# mora biti /images/ osim ako nisi stavio u main, ali NE stavljaj tamo!
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b> BASIC INFO <b/>
  Age: 19
  <br>
  Nationality: Croatian
  <br><br>
  
  <b> Programming skills <b/>
  <br>
  - Unity C#
  <br>
  - Ren'py
  <br><br>
  
  <b> Software <b/>
  <br>
  - Adobe Photoshop
  <br>
  - Clip Studio Paint PRO / EX
  <br>
  - Blender
  <br>
  - Krita
  <br><br>
  
  <b> Languages <b/>
  English
  Croatian (Native)
  Japanese (A1)
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
