title: Ivana Rebić # your name (or website title) here
# logo: "/images/logo.png?raw=true" # your photo (or logo) here/ umjesto logo.png ise ime foldera gdje se nalazi pa onda jepg ako je takva slika
# mora biti /images/ osim ako nisi stavio u main, ali NE stavljaj tamo!
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b> BASIC INFO </b>
  <br>
  Age: 19
  <br>
  Nationality: Croatian
  <br><br>
  
  <b> Programming skills </b>
  <br>
  - Unity C#
  <br>
  - NaniNovel (Extension for Unity)
  <br>
  - Ren'py
  <br><br>
  
  <b> Software </b>
  <br>
  - Adobe Photoshop
  <br>
  - Clip Studio Paint PRO / EX
  <br>
  - Blender
  <br>
  - Krita
  <br>
  - Draw.io
  <br><br>
  
  <b> Languages </b>
  <br>
  English
  <br>
  Croatian (Native)
  <br>
  Japanese (A1)
  <br><br>
  
  <b> Accounts </b>
  <br>
  https://rebic.itch.io/
  <br><br>
  
  <b> Contact </b>
  <br>
  :e-mail: Mail: ivana.rebic01@gmail.com
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
